spring.profiles.active=local
account.switch-name=virtual-account-manager
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/accountmanagerdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/ca
spring.application.name=virtual-account-manager
service.name=virtual-account-manager
management.health.redis.enabled=false

#metrix
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
wrappers.prometheus.enable=true

logging.level.reactor.netty.http.client.HttpClient=DEBUG

opentracing.jaeger.const-sampler.decision=true
opentracing.jaeger.enabled=false
opentracing.jaeger.log-spans=false

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.com.keelean.accountmanager=DEBUG

#logging.level.root=DEBUG

#AES Properties
aes.salt=${AES_SALT:}
aes.passphrase=${AES_PASSPHRASE:}
aes.init-vector=${AES_INIT_VECTOR:}

#spring.cloud.consul.enabled=false

#kafka
kafka.notify-topic=NOTIFY_ALERT_REQ_TOPIC
kafka.default-topic=NOTIFY_ALERT_REQ_TOPIC
kafka.consumer-transaction-topic=transaction_store
kafka.consumer-llm-user-optin-topic=llm-user-optin

#Kafka settings
spring.kafka.consumer.group-id=ca-group-1
kafka.bootstrap-server=localhost:9092
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=latest
kafka.listen.auto.start=true
spring.kafka.consumer.kafka-concurrent-size=5

#############RETRY PROPERTIES################
retry.count=3
retry.delay=6000
retry.initial-interval=60000
retry.interval-multiplier=1
retry.max-interval=300000
#############################################

#flyway
spring.flyway.enabled=true
flyway.enabled=true
flyway.baseline-on-migrate=true

management.endpoint.health.show-details=always

#======================================================
#SPRING BOOT ADMIN SERVER CONFIGURATION
#=======================================================
spring.boot.admin.enabled=true

spring.security.user.name=admin
spring.security.user.password=admin

#configs to connect to a secured server
spring.boot.admin.client.url=http://localhost:9091/admin-server
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=${ADMIN_CLIENT_PASSWORD:}

#configs to give secured server info
spring.boot.admin.client.instance.metadata.user.name=${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password=${spring.security.user.password}
spring.boot.admin.routes.endpoints=env, metrics, trace, jolokia, info, configprops

#redis
spring.cache.type=redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.redis.timeout=60000
spring.redis.database=0
spring.cache.redis.cache-null-values=false

#Keys
account.secret-key=${ACCOUNT_SECRET_KEY:}

#Fileds to Encrypt
account.encrypt-fields=id_number, kraPin
kafka.ca.groupId=ca

#accountAccount Config
va-pool.prefix-series.allow-multiple-open-pool=false
va-pool.prefix-series.allow-creation-unutilized=false
va-pool.prefix-series.range=30,31,32,33,34,35,36,37,38,39, 40, 42
va-pool.dynamic.allowed-bucket-capacity=SHARED_POOL_10, THOUSAND_10, THOUSAND_100, MILLION_1, MILLION_10, MILLION_100
va-pool.static.allowed-bucket-capacity=SHARED_POOL_1, THOUSAND_10, THOUSAND_100, MILLION_1
#controls the total count of partners in a shared pool prefix
va-pool.static.shared-pool-max-partners=1000
va-pool.dynamic.shared-pool-max-partners=1000

va-partner.dynamic.de-allocation.cooldown-range-days=30,60,90
#this setting is mandatory used for shared-pool
va-partner.dynamic.de-allocation.used-account-cooldown-days.default=90
va-partner.dynamic.de-allocation.unused-account-cooldown-days=1

va-partner.static.de-allocation.cooldown-range-days=180,270,365
va-partner.static.de-allocation.used-account-cooldown-days.default=365
va-partner.static.de-allocation.unused-account-cooldown-days=5

va-partner.settlement.product-code=INSTANT,EOD,TPLUS1,TPLUS2,TPLUS3,TPLUS5
va-partner.dynamic.shared-pool.bucket-capacity=1000
va-partner.static.shared-pool.bucket-capacity=1000

va-customer.dynamic.van.maximum-inactive-hrs=24
va-customer.static.van.maximum-inactive-days=180
va-customer.static.van.force-wait-after-edit-hrs=1
