package com.keelean.legacy.customeraccounts.exception;

import lombok.Getter;

@Getter
public enum  ErrorCodes {

  INVALID_COUNTRY_CODE("CA400"),
  PRODUCT_DOES_NOT_EXIST("CA401"),
  ACCOUNT_DOES_NOT_EXIST("CA402"),
  ACCOUNT_NUMBER_NOT_PRESENT("CA403"),
  VALIDATION_FAILED("CA404"),
  INVALID_ACCOUNT_STATUS("CA405"),
  CUSTOMER_FOR_MSISDN_DOES_NOT_EXIST("CA406"),
  DOWNSTREAM_API_ERROR("CA407"),
  INVALID_CREDENTIALS("CA408"),
  MULTIPLE_ACCOUNTS_EXIST("CA409"),
  CLIENT_FALLBACK_ERROR("CA410"),
  ACTIVE_ACCOUNT_DOESNT_EXISTS("CA411"),
  UNABLE_TO_SEND_CALLBACK_NOTIFICATION("CA412"),
  ACCOUNT_CREATION_FAILED_ON_DOWNSTREAM("CA413"),
  UNABLE_TO_FETCH_KYC_DETAILS("CA414"),
  MISS_FIELDS_IN_USER_KYC_PROFILE_MAP("CA415"),
  INACTIVE_CUSTOMER_EXISTS("CA416"),
  ACCOUNT_ALREADY_IN_INACTIVE_STATE("CA417"),
  NO_ACTIVE_ACCOUNT("CA418"),
  INVALID_DATES("CA419"),
  INVALID_ACCOUNT_NUMBER("CA420"),
  DOWN_STREAM_TECHNICAL_ERROR("CA421"),
  INVALID_PARTNER_CODE("CA422"),
  ACCOUNT_NOT_FOUND("CA423"),
  OTP_VALIDATION_FAILED("CA424"),
  ACCOUNT_ALREADY_EXISTS("CA425"),
  NO_ACCOUNT_FOR_PARTNER_CODE("CA426"),
  USER_NOT_OPTED_IN("CA427"),
  ALREADY_OPTED_IN("CA428"),
  OPT_IN_DETAILS_NOT_PRESENT("CA429"),
  ONLY_ALLOWED_FOR_OPTIN_STATUS_INPROGRESS("CA430"),
  NON_SUCCESS_RESONSE("CA431"),
  PRODUCT_KYC_SOURCE_MAPPING_NOT_FOUND("CA432"),
  USER_PROFILE_API_FAILED("CA433"),
  EN_LANG_ENTRY_NOT_PRESENT("CA434"),
  PRE_RULE_VALIDATION_FAIL("CA435"),
  MANDATORY_FIELDS_MISSING_IN_KYC_DETAILS_RESPONSE("CA436"),
  MISSING_DATA_FOR_LINKAGE_VALIDATION("CA437"),
  MANDATORY_PARAMETER_MISSING_IN_REQUEST("CA438"),
  NOTIFICATION_CONFIGURATION_ALREADY_EXISTS("CA439"),
  NO_NOTIFICATION_CONFIG_FOUND("CA440"),
  NOTIFICATION_CONFIG_ID_MISTATCH("CA441"),
  NOTIFICATION_CONFIG_UPDATE_ALREADY_EXISTS("CA442"),
  INVALID_NOTIFICATION_CONFIG_REQUEST("CA443"),
  NOTIFICATION_SEND_FAILURE_NO_TEMPLATE_NAME_PRESENT("CA444"),
  NOTIFICATION_SEND_FAILURE_NO_NOTIFICATION_CONFIG_PRESENT("CA445"),
  NO_NOTIFICATION_TEMPLATE_EXISTS("CA446"),
  NO_EXISTING_ACCOUNT("CA447"),
  KYC_VALIDATE_MSISDN_FAILURE("CA301"),
  NO_DATA_FROM_LAST_TRANSACTION_API_RESPONSE("CA302"),
  KYC_DETAILS_MISSING_USER_STATUS("CA303"),
  NO_USER_FOUND_IN_KYC("CA304"),
  FIELDS_ENCRYPTION_ERR("CA305"),
  INTERNAL_SERVER_ERROR_DETAILS("CA306"),
  INVALID_OR_EMPTY_ACCOUNT_ID_OR_REFERENCE("CA307"),
  PARTNER_CONFIG_DOES_NOT_EXIST("CA308"),
  ACCOUNT_NAME_VALIDATION_FAILED("CA309"),
  INVALID_ACCOUNT_RANGE("CA310"),
  ACCOUNT_LENGTH_VALIDATION("CA311"),
  INCOMPLETE_OR_WRONG_CONFIGURATION("CA312"),
  PARTNER_CONFIG_ALREADY_EXIST("CA313");

  private String code;

  ErrorCodes(String code) {
    this.code = code;
  }
}
