package com.keelean.accountmanager.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import java.util.Arrays;
import java.util.Optional;

import static org.springframework.http.HttpStatus.BAD_GATEWAY;
import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.CONFLICT;
import static org.springframework.http.HttpStatus.FORBIDDEN;
import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.http.HttpStatus.NOT_FOUND;
import static org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE;
import static org.springframework.http.HttpStatus.UNAUTHORIZED;

@Getter
public enum  ErrorCodes {

  INVALID_COUNTRY_CODE("CA400", BAD_REQUEST),
  PRODUCT_DOES_NOT_EXIST("CA401", NOT_FOUND),
  ACCOUNT_DOES_NOT_EXIST("CA402", NOT_FOUND),
  ACCOUNT_NUMBER_NOT_PRESENT("CA403", BAD_REQUEST),
  VALIDATION_FAILED("CA404", BAD_REQUEST),
  INVALID_ACCOUNT_STATUS("CA405", CONFLICT),
  CUSTOMER_FOR_MSISDN_DOES_NOT_EXIST("CA406", NOT_FOUND),
  DOWNSTREAM_API_ERROR("CA407", BAD_GATEWAY),
  INVALID_CREDENTIALS("CA408", UNAUTHORIZED),
  MULTIPLE_ACCOUNTS_EXIST("CA409", CONFLICT),
  CLIENT_FALLBACK_ERROR("CA410", SERVICE_UNAVAILABLE),
  ACTIVE_ACCOUNT_DOESNT_EXISTS("CA411", NOT_FOUND),
  UNABLE_TO_SEND_CALLBACK_NOTIFICATION("CA412", BAD_GATEWAY),
  ACCOUNT_CREATION_FAILED_ON_DOWNSTREAM("CA413", BAD_GATEWAY),
  UNABLE_TO_FETCH_KYC_DETAILS("CA414", BAD_GATEWAY),
  MISS_FIELDS_IN_USER_KYC_PROFILE_MAP("CA415", BAD_GATEWAY),
  INACTIVE_CUSTOMER_EXISTS("CA416", CONFLICT),
  ACCOUNT_ALREADY_IN_INACTIVE_STATE("CA417", CONFLICT),
  NO_ACTIVE_ACCOUNT("CA418", NOT_FOUND),
  INVALID_DATES("CA419", BAD_REQUEST),
  INVALID_ACCOUNT_NUMBER("CA420", BAD_REQUEST),
  DOWN_STREAM_TECHNICAL_ERROR("CA421", BAD_GATEWAY),
  INVALID_PARTNER_CODE("CA422", BAD_REQUEST),
  ACCOUNT_NOT_FOUND("CA423", NOT_FOUND),
  OTP_VALIDATION_FAILED("CA424", BAD_REQUEST),
  ACCOUNT_ALREADY_EXISTS("CA425", CONFLICT),
  NO_ACCOUNT_FOR_PARTNER_CODE("CA426", NOT_FOUND),
  USER_NOT_OPTED_IN("CA427", CONFLICT),
  ALREADY_OPTED_IN("CA428", CONFLICT),
  OPT_IN_DETAILS_NOT_PRESENT("CA429", NOT_FOUND),
  ONLY_ALLOWED_FOR_OPTIN_STATUS_INPROGRESS("CA430", CONFLICT),
  NON_SUCCESS_RESONSE("CA431", BAD_GATEWAY),
  PRODUCT_KYC_SOURCE_MAPPING_NOT_FOUND("CA432", NOT_FOUND),
  USER_PROFILE_API_FAILED("CA433", BAD_GATEWAY),
  EN_LANG_ENTRY_NOT_PRESENT("CA434", BAD_REQUEST),
  PRE_RULE_VALIDATION_FAIL("CA435", BAD_REQUEST),
  MANDATORY_FIELDS_MISSING_IN_KYC_DETAILS_RESPONSE("CA436", BAD_GATEWAY),
  MISSING_DATA_FOR_LINKAGE_VALIDATION("CA437", BAD_REQUEST),
  MANDATORY_PARAMETER_MISSING_IN_REQUEST("CA438", BAD_REQUEST),
  NOTIFICATION_CONFIGURATION_ALREADY_EXISTS("CA439", CONFLICT),
  NO_NOTIFICATION_CONFIG_FOUND("CA440", NOT_FOUND),
  NOTIFICATION_CONFIG_ID_MISTATCH("CA441", BAD_REQUEST),
  NOTIFICATION_CONFIG_UPDATE_ALREADY_EXISTS("CA442", CONFLICT),
  INVALID_NOTIFICATION_CONFIG_REQUEST("CA443", BAD_REQUEST),
  NOTIFICATION_SEND_FAILURE_NO_TEMPLATE_NAME_PRESENT("CA444", NOT_FOUND),
  NOTIFICATION_SEND_FAILURE_NO_NOTIFICATION_CONFIG_PRESENT("CA445", NOT_FOUND),
  NO_NOTIFICATION_TEMPLATE_EXISTS("CA446", NOT_FOUND),
  NO_EXISTING_ACCOUNT("CA447", NOT_FOUND),
  KYC_VALIDATE_MSISDN_FAILURE("CA301", FORBIDDEN),
  NO_DATA_FROM_LAST_TRANSACTION_API_RESPONSE("CA302", BAD_GATEWAY),
  KYC_DETAILS_MISSING_USER_STATUS("CA303", BAD_GATEWAY),
  NO_USER_FOUND_IN_KYC("CA304", NOT_FOUND),
  FIELDS_ENCRYPTION_ERR("CA305", INTERNAL_SERVER_ERROR),
  INTERNAL_SERVER_ERROR_DETAILS("CA306", INTERNAL_SERVER_ERROR),
  INVALID_OR_EMPTY_ACCOUNT_ID_OR_REFERENCE("CA307", BAD_REQUEST),
  PARTNER_CONFIG_DOES_NOT_EXIST("CA308", NOT_FOUND),
  ACCOUNT_NAME_VALIDATION_FAILED("CA309", BAD_REQUEST),
  INVALID_ACCOUNT_RANGE("CA310", BAD_REQUEST),
  ACCOUNT_LENGTH_VALIDATION("CA311", BAD_REQUEST),
  INCOMPLETE_OR_WRONG_CONFIGURATION("CA312", BAD_REQUEST),
  PARTNER_CONFIG_ALREADY_EXIST("CA313", CONFLICT);

  private String code;
  private HttpStatus status;

  ErrorCodes(String code, HttpStatus status) {
    this.code = code;
    this.status = status;
  }

  public static Optional<ErrorCodes> fromCode(String code) {
    return Arrays.stream(values()).filter(e -> e.code.equals(code)).findFirst();
  }
}
